workflows:
  ios-release:
    name: TDG iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Setup
        script: |
          cd ttt
          flutter pub get
      - name: Build iOS
        script: |
          cd ttt
          flutter build ipa --release --no-codesign
    artifacts:
      - ttt/build/ios/ipa/*.ipa
