// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhRrwEoZ_TxrtUpQ0lRYPa-M2cPLQBAE',
    appId: '1:784665159823:web:96634f5d9894c5ee90e8fa',
    messagingSenderId: '784665159823',
    projectId: 'tdg---otp',
    authDomain: 'tdg---otp.firebaseapp.com',
    storageBucket: 'tdg---otp.firebasestorage.app',
    measurementId: 'G-7Q1X3K2F9K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaH2A7MbCBwh5YyVVEhX9bcUQr6znUjok',
    appId: '1:784665159823:ios:d45482078a75cc6c90e8fa',
    messagingSenderId: '784665159823',
    projectId: 'tdg---otp',
    storageBucket: 'tdg---otp.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfhRrwEoZ_TxrtUpQ0lRYPa-M2cPLQBAE',
    appId: '1:784665159823:web:a40d07c5491ad44190e8fa',
    messagingSenderId: '784665159823',
    projectId: 'tdg---otp',
    authDomain: 'tdg---otp.firebaseapp.com',
    storageBucket: 'tdg---otp.firebasestorage.app',
    measurementId: 'G-VBP1T7NGF3',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaH2A7MbCBwh5YyVVEhX9bcUQr6znUjok',
    appId: '1:784665159823:ios:d45482078a75cc6c90e8fa',
    messagingSenderId: '784665159823',
    projectId: 'tdg---otp',
    storageBucket: 'tdg---otp.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26pzTDtoq33JZ7mCCDCCxhGDRe0zS-8c',
    appId: '1:784665159823:android:3001abe5f094d79b90e8fa',
    messagingSenderId: '784665159823',
    projectId: 'tdg---otp',
    storageBucket: 'tdg---otp.firebasestorage.app',
  );
}
